In [79]:
import pandas as pd
import numpy as np

# 1. Pandas Version

In [80]:
pd.__version__


'2.3.2'

In [81]:
car_df = pd.read_csv("car_fuel_efficiency.csv")

# 2. How many records are in the dataset?
How many records are in the dataset?

In [82]:
car_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


# 3. Fuel types
How many fuel types are presented in the dataset?

In [83]:
car_df["fuel_type"].value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

# 4. Missing values
How many columns in the dataset have missing values?

In [84]:
car_df.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

# 5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [85]:
asia_df = car_df.loc[car_df["origin"] == "Asia"]
asia_df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [86]:
asia_df.describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          3247.000000    3099.000000  3013.000000     3247.000000   
mean            200.052356       4.010326   150.303352     3006.292228   
std              49.287252       1.971199    30.257169      502.434626   
min              30.000000       0.000000    40.000000     1223.298226   
25%             170.000000       3.000000   130.000000     2665.518985   
50%             200.000000       4.000000   150.000000     2988.585737   
75%             230.000000       5.000000   171.000000     3345.355571   
max             370.000000      11.000000   245.000000     4661.144932   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   2933.000000  3247.000000  3072.000000          3247.000000  
mean      15.036754  2011.489375    -0.001628            14.973830  
std        2.488340     6.704607     1.051428             2.578345  
min        6.400000  2000.000000    -4.000000             6.886245  
25%       13.300000  2006.000000    -1.000000            13.252010  
50%       15.100000  2012.000000     0.000000            15.034670  
75%       16.700000  2017.000000     1.000000            16.726318  
max       22.700000  2023.000000     4.000000            23.759123

# 6. Median value of horsepower
* Find the median value of horsepower column in the dataset.
* Next, calculate the most frequent value of the same horsepower column.
* Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
* Now, calculate the median value of horsepower once again.
* Has it changed?



In [87]:
car_df.describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          9704.000000    9222.000000  8996.000000     9704.000000   
mean            199.708368       3.962481   149.657292     3001.280993   
std              49.455319       1.999323    29.879555      497.894860   
min              10.000000       0.000000    37.000000      952.681761   
25%             170.000000       3.000000   130.000000     2666.248985   
50%             200.000000       4.000000   149.000000     2993.226296   
75%             230.000000       5.000000   170.000000     3334.957039   
max             380.000000      13.000000   271.000000     4739.077089   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   8774.000000  9704.000000  9202.000000          9704.000000  
mean      15.021928  2011.484027    -0.006412            14.985243  
std        2.510339     6.659808     1.048162             2.556468  
min        6.000000  2000.000000    -4.000000             6.200971  
25%       13.300000  2006.000000    -1.000000            13.267459  
50%       15.000000  2012.000000     0.000000            15.006037  
75%       16.700000  2017.000000     1.000000            16.707965  
max       24.300000  2023.000000     4.000000            25.967222

In [88]:
car_df["horsepower"].mean()

np.float64(149.65729212983547)

In [89]:
car_df["horsepower"].value_counts().head()

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
Name: count, dtype: int64

In [90]:
car_df["horsepower2"] = car_df["horsepower"]

In [91]:
car_df["horsepower2"] = car_df["horsepower2"].fillna(152.0)

In [92]:
car_df["horsepower2"].isna().sum()

np.int64(0)

In [93]:
car_df["horsepower2"].mean()

np.float64(149.82821516900248)

# 7. Sum of weights
* Select all the cars from Asia
* Select only columns vehicle_weight and model_year
* Select the first 7 values
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
* Invert XTX.
* Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
* Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
* What's the sum of all the elements of the result?

In [111]:
car_df[car_df["origin"] == "Asia"][["vehicle_weight","model_year"]].head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [141]:
X = car_df[car_df["origin"] == "Asia"][["vehicle_weight","model_year"]].head(7).to_numpy()

In [142]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [145]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150761, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [147]:
XTX_inverse =np.linalg.inv(XTX)
XTX_inverse

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [150]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [151]:
w = XTX_inverse.dot(X.T).dot(y)
w

array([0.01386421, 0.5049067 ])

In [152]:
w.sum()

np.float64(0.5187709081074006)